 
CREATE DATABASE DuAn1_QuanLiBanQuanAo
GO
USE DuAn1_QuanLiBanQuanAo
GO 
---ChucVu
CREATE TABLE ChucVu (
IdCV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaChucVu VARCHAR(20) UNIQUE,
ChucVu NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 1,
)
GO
-- NhanVien
CREATE TABLE NhanVien(
IdNV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNV VARCHAR(20) UNIQUE,
TenNV NVARCHAR(30) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
MatKhau VARCHAR(MAX) DEFAULT NULL,
TrangThai INT DEFAULT 0,
IdCV UNIQUEIDENTIFIER
)
GO
-- KhachHang
CREATE TABLE KhachHang(
IdKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaKH VARCHAR(20) UNIQUE,
Ten NVARCHAR(30),
TenDem NVARCHAR(30) DEFAULT NULL,
Ho NVARCHAR(30) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
ThanhPho NVARCHAR(50) DEFAULT NULL,
QuocGia NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 1,
)
GO
--HoaDon
CREATE TABLE HoaDon(
IdHoaDon UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
IdPTTT UNIQUEIDENTIFIER,
MaHD VARCHAR(20) UNIQUE,
NgayTao DATE DEFAULT NULL,
NgayThanhToan DATE DEFAULT NULL,
NgayHen DATE DEFAULT NULL,
NgayShip DATE DEFAULT NULL,
NgayNhan DATE DEFAULT NULL,
TenNguoiNhan NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
TrangThai INT DEFAULT 0,
Sdt VARCHAR(30) DEFAULT NULL,
)
GO
-- SanPham
CREATE TABLE SanPham(
IdSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaSP VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- NSX
CREATE TABLE NSX(
IdNSX UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- MauSac
CREATE TABLE MauSac(
IdMauSac UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
TenMauSac NVARCHAR(30)
)
GO
-- ChatLieu
CREATE TABLE ChatLieu(
IdChatLieu UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
TenChatLieu NVARCHAR(30)
)
GO
-- ThuongHieu
CREATE TABLE ThuongHieu(
IdThuongHieu UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
TenChatLieu NVARCHAR(30)
)
GO
-- Size
CREATE TABLE Size(
IdSize UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
SoSize INT
)
GO
-- LoaiSanPham
CREATE TABLE LoaiSanPham(
IdLoaiSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenLoaiSP NVARCHAR(30)
)

GO
-- ChiTietSP
CREATE TABLE ChiTietSP(
IdCTSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdSP UNIQUEIDENTIFIER,
IdNSX UNIQUEIDENTIFIER,
IdMauSac UNIQUEIDENTIFIER,
IdLoaiSP UNIQUEIDENTIFIER,
IdChatLieu UNIQUEIDENTIFIER,
IdThuongHieu UNIQUEIDENTIFIER,
IdSize UNIQUEIDENTIFIER,
SoLuong INT,
GiaNhap DECIMAL(20,0) DEFAULT 0,
GiaBan DECIMAL(20,0) DEFAULT 0,
MoTa NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 1,
)
GO

GO
-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
IdHoaDon UNIQUEIDENTIFIER,
IdCTSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HoaDonCT PRIMARY KEY (IdHoaDon,IdCTSP),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(IdHoaDon),
CONSTRAINT FK2 FOREIGN KEY(IdCTSP) REFERENCES ChiTietSP(IdCTSP),
)
GO
-- LoaiHinhTT
CREATE TABLE LoaiHinhTT(
IdLHTT UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenLHTT NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 1,
)
-- PTTT
CREATE TABLE PTTT(
IdHoaDon UNIQUEIDENTIFIER,
IdLHTT UNIQUEIDENTIFIER,
SoTien MONEY NULL,
CONSTRAINT PK_PTTT PRIMARY KEY (IdHoaDon,IdLHTT),
CONSTRAINT FK_PTTT_LHTT FOREIGN KEY(IdLHTT) REFERENCES dbo.LoaiHinhTT(IdLHTT),
CONSTRAINT FK_PTTT_HoaDon FOREIGN KEY(IdHoaDon) REFERENCES dbo.HoaDon(IdHoaDon),
)
GO
--TẠO QUAN HỆ GIỮA CÁC BẢNG
--NhanVien - ChucVu
ALTER TABLE NhanVien ADD FOREIGN KEY (IdCV) REFERENCES dbo.ChucVu(IdCV)
--HoaDon - NhanVien
ALTER TABLE dbo.HoaDon ADD FOREIGN KEY (IdNV) REFERENCES dbo.NhanVien(IdNV)
--HoaDon - KhachHang
ALTER TABLE dbo.HoaDon ADD FOREIGN KEY (IdKH) REFERENCES dbo.KhachHang(IdKH)
--CTSP - Thuong Hieu
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdThuongHieu) REFERENCES dbo.ThuongHieu(IdThuongHieu)
--CTSP - Size
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdSize) REFERENCES dbo.Size(IdSize)
--CTSP - LoaiSP
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdLoaiSP) REFERENCES dbo.LoaiSanPham(IdLoaiSP)
--CTSP - ChatLieu
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdChatLieu) REFERENCES dbo.ChatLieu(IdChatLieu)
--CTSP - NSX
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdNSX) REFERENCES dbo.NSX(IdNSX)
--CTSP - MauSac
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdMauSac) REFERENCES dbo.MauSac(IdMauSac)
--CTSP - SanPham
ALTER TABLE dbo.ChiTietSP ADD FOREIGN KEY (IdSP) REFERENCES dbo.SanPham(IdSP)



------Update 1.1
-----Insert Các bảng
ALTER TABLE dbo.Size
ALTER COLUMN SoSize NVARCHAR(50);
-----Insert Các bảng
-----Insert Bảng Chất Liệu
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL01' ,N'Vải Cotton' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL02' ,N'Vải Kaki' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL03' ,N'Vải Jeans' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL04' ,N'Vải Kate' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL05' ,N'Vải Nỉ' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL06' ,N'Vải Len' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL07' ,N'Vải Thô' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL08' ,N'Vải Voan' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL09' ,N'Vải Lanh' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL10' ,N'Vải Đũi' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL11' ,N'Vải Ren' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL13' ,N'Vải FE' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL14' ,N'Vải Nỉ Lông' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL15' ,N'Vải Spandex' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL16' ,N'Vải Hoa Văn' )
INSERT INTO dbo.ChatLieu (IdChatLieu,Ma,TenChatLieu) VALUES (   DEFAULT, N'CL17' ,N'Vải Thun Lạnh' )
-----Insert Bảng NSX
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N001', N'Công Ty Cổ Phần May Đồng Na')

-----Insert Bảng Size
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'XXS')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'XS')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'S')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'M')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'L')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'XL')
INSERT INTO dbo.Size (IdSize,SoSize) VALUES (DEFAULT, N'XXL')

-----Insert Bảng Thương Hiệu
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT01',N'Jody')
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT02',N'Việt Tiến')
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT03',N'May10')
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT04',N'Owen')
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT05',N'CoolMate')
INSERT INTO dbo.ThuongHieu (IdThuongHieu,Ma,TenChatLieu) VALUES (DEFAULT,N'TT06',N'Top4Man')
-----Insert Bảng Chức Vụ
INSERT INTO dbo.ChucVu (IdCV,MaChucVu,ChucVu,TrangThai) VALUES (DEFAULT,N'CV01',N'Admin',1)
INSERT INTO dbo.ChucVu (IdCV,MaChucVu,ChucVu,TrangThai) VALUES (DEFAULT,N'CV02',N'NhanVien',1)
SELECT IdCV FROM dbo.ChucVu WHERE ChucVu = N'NhanVien'

------Update 1.2
-----Sửa tên bảng thương hiệu
ALTER TABLE dbo.ThuongHieu
DROP COLUMN TenChatLieu
ALTER TABLE dbo.ThuongHieu
ADD  TenThuongHieu NVARCHAR(50);
--- Insert TenthuongHieu
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'Jody' WHERE Ma = N'TT01'
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'Việt Tiến' WHERE Ma = N'TT02'
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'May10' WHERE Ma = N'TT03'
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'Owen' WHERE Ma = N'TT04'
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'CoolMate' WHERE Ma = N'TT05'
UPDATE dbo.ThuongHieu SET TenThuongHieu = N'Top4Man' WHERE Ma = N'TT06'
---Insert bảng NSX
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N002', N'Công Ty Cổ Phần Dệt 10/10')
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N003', N'Công Ty Cổ Phần May Sông Hồng')
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N004', N'Công ty cổ phần Dệt-May 29/3')
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N005', N'Tập đoàn dệt may Việt Nam')
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N006', N'Tổng công ty dệt may Hà Nội')
INSERT INTO dbo.NSX (IdNSX,Ma,Ten) VALUES ( DEFAULT, N'N007', N'Công ty cổ phần may Việt Tiến')